{\rtf1\ansi\ansicpg1252\cocoartf1265\cocoasubrtf210
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;\red16\green19\blue26;\red244\green245\blue246;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720

\f0\fs24 \cf2 \cb3 search:\
	g++ search.cpp -o search\
\
generator:\
	g++ input-gen.cpp -o generator\
\
clean:\
	rm *.o}